export default [
  {
    id: '1001',
    mpid: '-1',
    icon: 'laptop',
    name: '首页',
    route: '/',
  },
  {
    id: '1002',
    mpid: '-1',
    name: '微信用户',
    icon: 'message',
    route: '/wxuserdetail',
  },
  {
    id: '1003',
    mpid: '-1',
    name: '门店操作人详情',
    route: '/storeuserDetail',
  },
  {
    id: '1004',
    mpid: '-1',
    name: '操作人寄件汇总',
    route: '/operator',
  },
  {
    id: '1005',
    mpid: '-1',
    name: '门店单号汇总',
    route: '/expressfeedetail',
  },
  {
    id: '1006',
    mpid: '-1',
    name: '操作人',
    route: '/operatorbyname',
  },
  {
    id: '1007',
    mpid: '-1',
    name: '快件详情',
    route: '/orderbyuser',
  },
  {
    id: '1008',
    mpid: '-1',
    name: '操作人分派详情',
    route: '/selectpjjeDetails',
  },
  {
    id: '1009',
    mpid: '-1',
    name: '门店问题件明细',
    route: '/problemdetail',
  },
  {
    id: '1010',
    mpid: '-1',
    name: '二维码图片',
    route: '/qrdetail',
  },
  {
    id: '1011',
    mpid: '-1',
    name: '业务量详情',
    route: '/businessvolumeDetail',
  },
  {
    id: '1012',
    mpid: '-1',
    name: '分派人详情',
    route: '/assignor',
  },
  {
    id: '1013',
    mpid: '-1',
    name: '接口对接明细',
    icon: 'message',
    route: '/dockingdetail',
  },
  {
    id: '1014',
    mpid: '-1',
    name: '通讯费消费账单明细',
    icon: 'message',
    route: '/communicationbilldetail',
  },
  {
    id: '1015',
    mpid: '-1',
    name: '短信状态明细查询',
    icon: 'message',
    route: '/messagearrivedetail',
  },

  {
    id: '100150101',
    mpid: '-1',
    name: '门店寄件历史数据明细查询',
    route: '/backupexpressfeedetail',
  }, {
    id: '100150102',
    mpid: '-1',
    name: '门店寄件历史数据明细查询',
    route: '/backupstoreuserdetail',
  }, {
    id: '100150201',
    mpid: '-1',
    name: '操作人历史数据查询',
    route: '/backupoperatorbyname',
  }, {
    id: '100150202',
    mpid: '-1',
    name: '门店操作单号历史数据查询',
    route: '/backuporderbyuser',
  }, {
    id: '100150301',
    mpid: '-1',
    name: '门店分派-操作',
    route: '/backupassignor',
  }, {
    id: '100150301',
    mpid: '-1',
    name: '门店分派-订单明细',
    route: '/backupselectpjjeDetails',
  }, {
    id: '100150401',
    mpid: '-1',
    name: '业务量-订单明细',
    route: '/backupbusinessvolumedetail',
  },
]
