export default [
  {
    id: '1001',
    mpid: '-1',
    icon: 'laptop',
    name: '首页',
    route: '/',
  },
  {
    id: '1002',
    mpid: '-1',
    name: '微信用户',
    icon: 'message',
    route: '/wxuserdetail',
  },
  {
    id: '1003',
    mpid: '-1',
    name: '门店操作人详情',
    route: '/storeuserDetail',
  },
  {
    id: '1004',
    mpid: '-1',
    name: '操作人寄件汇总',
    route: '/operator',
  },
  {
    id: '1005',
    mpid: '-1',
    name: '门店单号汇总',
    route: '/expressfeedetail',
  },
  {
    id: '1006',
    mpid: '-1',
    name: '操作人',
    route: '/operatorbyname',
  },
  {
    id: '1007',
    mpid: '-1',
    name: '快件详情',
    route: '/orderbyuser',
  },
  {
    id: '1008',
    mpid: '-1',
    name: '操作人分派详情',
    route: '/selectpjjeDetails',
  },
  {
    id: '1009',
    mpid: '-1',
    name: '门店问题件明细',
    route: '/problemdetail',
  },
  {
    id: '1010',
    mpid: '-1',
    name: '二维码图片',
    route: '/qrdetail',
  },
  {
    id: '1011',
    mpid: '-1',
    name: '业务量详情',
    route: '/businessvolumeDetail',
  },
  {
    id: '1012',
    mpid: '-1',
    name: '分派人详情',
    route: '/assignor',
  },
  {
    id: '1013',
    mpid: '-1',
    name: '接口对接明细',
    icon: 'message',
    route: '/dockingdetail',
  },
  {
    id: '1014',
    mpid: '1',
    name: '对接管理',
    icon: 'message',
  },
  {
    id: '101401',
    mpid: '1014',
    name: '快递对接',
    icon: 'message',
    route: '/docking',
  },
  {
    id: '101402',
    mpid: '1014',
    name: '品牌对接',
    icon: 'message',
    route: '/branddocking',
  },
]
